apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    chart: eck-operator
    helm:
      installCRDs: true
      prometheus:
        enabled: true
    repoURL: https://charts.jetstack.io
    targetRevision: 1.9.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
