apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  project: default
  source:
    chart: eck-operator
    helm:
    repoURL: https://helm.elastic.co
    targetRevision: 2.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
