apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns-system
  project: default
  source:
    chart: external-dns
    helm:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.8.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
