apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-config
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    path: manifests/configs/generic
    repoURL: https://github.com/Jubblin/argocd_k3s-ha.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
