apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: kong
    helm:
    repoURL: https://charts.konghq.com
    targetRevision: 2.12.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
