apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: kubed
    helm:
    repoURL: https://charts.appscode.com/stable/
    targetRevision: v0.12.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
