apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  project: default
  source:
    chart: loki
    helm:
      values: |
        gateway:
          service:
            type: LoadBalancer
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
