apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  project: default
  source:
    chart: metallb
    helm:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.4    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true