apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root_of_apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: apps/
    repoURL: https://github.com/Jubblin/argocd_k3s-ha.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
