apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/configs/system-upgrade-controller
    repoURL: https://github.com/Jubblin/argocd_k3s-ha.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
