apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: whoami.n6.bonkie.net
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: 80
