argo-cd:
  dex:
    enabled: false
  server:
    service:
      type: LoadBalancer
    extraArgs:
    - --insecure
    config:
      repositories: |
        - name: argo-cd
          type: helm
          url: https://argoproj.github.io/argo-helm
  metrics:
    # -- Deploy metrics service
    enabled: true
