# sc-nfs.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.2.250.229
  share: /volume1/k8s
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nolock